sudo: required
dist: xenial
language: cpp

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - export CC=gcc-4.8
  - export CXX=g++-4.8
  - printenv
  - sudo apt-get install libopenblas-dev
  - wget https://launchpad.net/ubuntu/+archive/primary/+files/armadillo_6.500.5+dfsg.orig.tar.gz && tar xf armadillo_6.500.5+dfsg.orig.tar.gz
  - cd armadillo_6.500.5 && cmake . && make && sudo make install && cd ..
  - sudo cp .travis/config.hpp /usr/include/armadillo_bits/config.hpp
install:
  - mkdir build && cd build && cmake -DDEBUG=OFF -DPROFILE=OFF .. && make -j2

script:
  - CTEST_OUTPUT_ON_FAILURE=1 travis_wait 30 ctest -j2

notifications:
  email:
    - mlpack-git@lists.mlpack.org
  irc:
    channels:
      - "chat.freenode.net#mlpack"
    on_success: change
    on_failure: always
